#!/usr/bin/env python3
# Paradox Hypersonic Elixir 360 AIO LCD — tray + settings GUI
import glob
import importlib.util
import os
import subprocess

import gi

gi.require_version("Gtk", "3.0")
from gi.repository import Gtk, GLib  # noqa: E402

UNIT = "aio-lcd.service"
CFG = os.path.expanduser("~/.config/aio-lcd.conf")
ICON = "org.gnome.SystemMonitor"


def _load_feeder():
    here = os.path.dirname(os.path.abspath(__file__))
    for path in (os.path.join(here, "aio-lcd.py"),
                 os.path.expanduser("~/.local/bin/aio-lcd.py")):
        if os.path.isfile(path):
            spec = importlib.util.spec_from_file_location("aio_lcd", path)
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            return mod
    raise SystemExit("aio-lcd.py not found (run install.sh first)")


feeder = _load_feeder()


def systemctl(*args):
    return subprocess.run(
        ["systemctl", "--user", *args],
        capture_output=True, text=True, timeout=5,
    )


def service_active():
    return systemctl("is-active", UNIT).stdout.strip() == "active"


def service_state():
    out = systemctl("is-active", UNIT).stdout.strip()
    return out or "unknown"


def discover_gpu():
    opts = [("auto", "auto (first available)")]
    try:
        r = subprocess.run(
            ["nvidia-smi", "--query-gpu=index,name,temperature.gpu",
             "--format=csv,noheader"],
            capture_output=True, text=True, timeout=2,
        )
        for line in r.stdout.splitlines():
            parts = [p.strip() for p in line.split(",")]
            if len(parts) < 3:
                continue
            idx, name, temp = parts[0], parts[1], parts[2]
            opts.append((f"nvidia:{idx}",
                         f"{name} (index {idx}, {temp}°C)"))
    except Exception:
        pass
    for h in glob.glob("/sys/class/hwmon/hwmon*"):
        try:
            name = open(h + "/name").read().strip()
        except Exception:
            continue
        if name not in ("amdgpu", "i915", "xe"):
            continue
        for tf in sorted(glob.glob(h + "/temp*_input")):
            base = os.path.basename(tf)
            lab = "?"
            lf = tf.replace("_input", "_label")
            if os.path.isfile(lf):
                try:
                    lab = open(lf).read().strip()
                except Exception:
                    pass
            try:
                temp = int(open(tf).read()) // 1000
            except Exception:
                temp = 0
            opts.append((f"{name}:{base}",
                         f"{name} {base} ({lab}, {temp}°C)"))
    return opts


def discover_fan():
    opts = [("auto", "auto (chip default / first nonzero)")]
    for h in sorted(glob.glob("/sys/class/hwmon/hwmon*")):
        try:
            name = open(h + "/name").read().strip()
        except Exception:
            continue
        for f in sorted(glob.glob(h + "/fan*_input")):
            base = os.path.basename(f)
            lab = "-"
            lf = f.replace("_input", "_label")
            if os.path.isfile(lf):
                try:
                    lab = open(lf).read().strip()
                except Exception:
                    pass
            try:
                rpm = int(open(f).read())
            except Exception:
                rpm = 0
            opts.append((f"{name}/{base}",
                         f"{name} {base} (label={lab}, {rpm} RPM)"))
    return opts


def read_cfg_values():
    gpu, fan = "auto", "auto"
    try:
        for line in open(CFG):
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            k, v = k.strip(), v.strip()
            if k == "GPU" and v:
                gpu = v
            elif k == "FAN" and v:
                fan = v
    except Exception:
        pass
    return gpu, fan


def write_cfg(gpu, fan):
    os.makedirs(os.path.dirname(CFG), exist_ok=True)
    with open(CFG, "w") as f:
        f.write(
            "# Paradox AIO LCD — generated by aio-lcd-gui\n"
            "# GPU: auto | nvidia:<index> | amdgpu:<tempN_input> | "
            "i915:<tempN_input> | xe:<tempN_input>\n"
            "# FAN: auto | <chip>/<fanN_input>\n"
            f"GPU={gpu}\n"
            f"FAN={fan}\n"
        )


def _combo_fill(combo, options, selected):
    store = Gtk.ListStore(str, str)  # id, label
    active = 0
    for i, (oid, label) in enumerate(options):
        store.append([oid, label])
        if oid == selected:
            active = i
    combo.clear()
    combo.set_model(store)
    renderer = Gtk.CellRendererText()
    combo.pack_start(renderer, True)
    combo.add_attribute(renderer, "text", 1)
    combo.set_active(active)


def _combo_id(combo):
    it = combo.get_active_iter()
    if it is None:
        return None
    return combo.get_model()[it][0]


class SettingsDialog(Gtk.Dialog):
    def __init__(self, parent):
        super().__init__(title="AIO LCD Settings", transient_for=parent,
                         modal=True)
        self.set_default_size(480, 180)
        self.add_button("_Cancel", Gtk.ResponseType.CANCEL)
        self.add_button("_Save & Restart", Gtk.ResponseType.OK)
        self.set_default_response(Gtk.ResponseType.OK)

        grid = Gtk.Grid(column_spacing=12, row_spacing=10, margin=16)
        self.get_content_area().pack_start(grid, True, True, 0)

        gpu_val, fan_val = read_cfg_values()

        grid.attach(Gtk.Label(label="GPU temp", xalign=0), 0, 0, 1, 1)
        self.gpu_combo = Gtk.ComboBox()
        _combo_fill(self.gpu_combo, discover_gpu(), gpu_val)
        grid.attach(self.gpu_combo, 1, 0, 1, 1)

        grid.attach(Gtk.Label(label="Fan / pump", xalign=0), 0, 1, 1, 1)
        self.fan_combo = Gtk.ComboBox()
        _combo_fill(self.fan_combo, discover_fan(), fan_val)
        grid.attach(self.fan_combo, 1, 1, 1, 1)

        refresh = Gtk.Button(label="Refresh sensors")
        refresh.connect("clicked", self._on_refresh)
        grid.attach(refresh, 1, 2, 1, 1)

        self.gpu_combo.set_hexpand(True)
        self.fan_combo.set_hexpand(True)
        self.show_all()

    def _on_refresh(self, _btn):
        gpu = _combo_id(self.gpu_combo) or "auto"
        fan = _combo_id(self.fan_combo) or "auto"
        _combo_fill(self.gpu_combo, discover_gpu(), gpu)
        _combo_fill(self.fan_combo, discover_fan(), fan)

    def values(self):
        return _combo_id(self.gpu_combo) or "auto", \
               _combo_id(self.fan_combo) or "auto"


class MainWindow(Gtk.Window):
    def __init__(self, app):
        super().__init__(title="Paradox AIO LCD")
        self.app = app
        self.set_default_size(360, 220)
        self.set_border_width(16)
        self.connect("delete-event", self._on_close)

        vbox = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=10)
        self.add(vbox)

        self.status_lbl = Gtk.Label(xalign=0)
        self.cpu_lbl = Gtk.Label(xalign=0)
        self.gpu_lbl = Gtk.Label(xalign=0)
        self.fan_lbl = Gtk.Label(xalign=0)
        for w in (self.status_lbl, self.cpu_lbl, self.gpu_lbl, self.fan_lbl):
            vbox.pack_start(w, False, False, 0)

        btn_row = Gtk.Box(spacing=8)
        vbox.pack_start(btn_row, False, False, 8)

        for label, cb in (
            ("Start", lambda *_: self.app.svc_start()),
            ("Stop", lambda *_: self.app.svc_stop()),
            ("Restart", lambda *_: self.app.svc_restart()),
            ("Settings", lambda *_: self.app.open_settings()),
        ):
            b = Gtk.Button(label=label)
            b.connect("clicked", cb)
            btn_row.pack_start(b, True, True, 0)

        hint = Gtk.Label(
            label="Close window to keep running in the tray.",
            xalign=0,
        )
        hint.get_style_context().add_class("dim-label")
        vbox.pack_start(hint, False, False, 0)

    def _on_close(self, *_args):
        self.hide()
        return True  # keep process alive (tray)

    def refresh(self, state, cpu, gpu, rpm):
        self.status_lbl.set_text(f"Service: {state}")
        self.cpu_lbl.set_text(f"CPU:  {cpu} °C")
        self.gpu_lbl.set_text(f"GPU:  {gpu} °C")
        self.fan_lbl.set_text(f"Fan:  {rpm} RPM")


class App:
    def __init__(self):
        self.window = MainWindow(self)
        self.indicator = None
        self.status_icon = None
        self._init_tray()
        self.window.show_all()
        GLib.timeout_add_seconds(1, self._tick)

    def _init_tray(self):
        # Prefer Ayatana AppIndicator when available
        for ns in ("AyatanaAppIndicator3", "AppIndicator3"):
            try:
                gi.require_version(ns, "0.1")
                mod = getattr(
                    __import__("gi.repository", fromlist=[ns]), ns
                )
                self.indicator = mod.Indicator.new(
                    "aio-lcd", ICON,
                    mod.IndicatorCategory.HARDWARE,
                )
                self.indicator.set_status(mod.IndicatorStatus.ACTIVE)
                self.indicator.set_menu(self._tray_menu())
                return
            except Exception:
                continue
        # Fallback: Gtk.StatusIcon
        self.status_icon = Gtk.StatusIcon.new_from_icon_name(ICON)
        self.status_icon.set_title("Paradox AIO LCD")
        self.status_icon.set_tooltip_text("Paradox AIO LCD")
        self.status_icon.connect("activate", lambda *_: self.show_window())
        self.status_icon.connect(
            "popup-menu", self._on_status_popup
        )

    def _tray_menu(self):
        menu = Gtk.Menu()
        items = (
            ("Show", self.show_window),
            ("Settings", self.open_settings),
            ("Start service", self.svc_start),
            ("Stop service", self.svc_stop),
            ("Restart service", self.svc_restart),
            ("Quit", self.quit),
        )
        for label, cb in items:
            item = Gtk.MenuItem(label=label)
            item.connect("activate", lambda _i, c=cb: c())
            menu.append(item)
        menu.show_all()
        return menu

    def _on_status_popup(self, _icon, button, activate_time):
        menu = self._tray_menu()
        menu.popup(None, None, Gtk.StatusIcon.position_menu,
                   self.status_icon, button, activate_time)

    def show_window(self, *_args):
        self.window.present()

    def open_settings(self, *_args):
        dlg = SettingsDialog(self.window if self.window.get_visible()
                             else None)
        if dlg.run() == Gtk.ResponseType.OK:
            gpu, fan = dlg.values()
            write_cfg(gpu, fan)
            feeder.load_cfg()
            self.svc_restart()
        dlg.destroy()

    def svc_start(self, *_a):
        systemctl("start", UNIT)

    def svc_stop(self, *_a):
        systemctl("stop", UNIT)

    def svc_restart(self, *_a):
        systemctl("restart", UNIT)

    def quit(self, *_a):
        Gtk.main_quit()

    def _tick(self):
        try:
            feeder.load_cfg()
            state = service_state()
            cpu = feeder.cpu_temp()
            gpu = feeder.gpu_temp()
            rpm = feeder.fan_rpm()
            self.window.refresh(state, cpu, gpu, rpm)
            tip = f"AIO LCD [{state}]  CPU {cpu}°  GPU {gpu}°  Fan {rpm}"
            if self.status_icon is not None:
                self.status_icon.set_tooltip_text(tip)
        except Exception:
            pass
        return True


def main():
    # single instance via display name is enough for this tool
    App()
    Gtk.main()


if __name__ == "__main__":
    main()
