#!/bin/sh
# Install Paradox AIO LCD native driver
set -e
DIR="$(cd "$(dirname "$0")" && pwd)"
CFG="$HOME/.config/aio-lcd.conf"

# Optional non-interactive: GPU=nvidia:0 FAN=nct6687/fan2_input ./install.sh
GPU_CHOICE="${GPU:-}"
FAN_CHOICE="${FAN:-}"

prompt_pick() {
    # $1=prompt  $2=default_index(1-based)  $3=max → prints selected 1-based index
    _prompt="$1"
    _def="$2"
    _max="$3"
    if [ "$_max" -le 0 ]; then
        echo 0
        return
    fi
    if [ "$_max" -eq 1 ]; then
        echo "  (only one option — selected)" >&2
        echo 1
        return
    fi
    while true; do
        printf "%s [%s]: " "$_prompt" "$_def" >&2
        read -r _ans || _ans=""
        [ -z "$_ans" ] && _ans="$_def"
        case "$_ans" in
            *[!0-9]*) echo "  enter a number 1-$_max" >&2; continue ;;
        esac
        if [ "$_ans" -ge 1 ] && [ "$_ans" -le "$_max" ]; then
            echo "$_ans"
            return
        fi
        echo "  enter a number 1-$_max" >&2
    done
}

pick_gpu() {
    _tmp="$(mktemp)"

    echo ""
    echo "Select GPU temperature source:"

    if command -v nvidia-smi >/dev/null 2>&1; then
        nvidia-smi --query-gpu=index,name,temperature.gpu --format=csv,noheader 2>/dev/null \
        | while IFS= read -r line; do
            [ -z "$line" ] && continue
            idx=$(echo "$line" | awk -F', *' '{print $1}')
            name=$(echo "$line" | awk -F', *' '{print $2}')
            temp=$(echo "$line" | awk -F', *' '{print $3}')
            printf 'nvidia:%s|%s (index %s, %s°C)\n' "$idx" "$name" "$idx" "$temp"
        done >> "$_tmp"
    fi

    for h in /sys/class/hwmon/hwmon*; do
        [ -f "$h/name" ] || continue
        name=$(cat "$h/name" 2>/dev/null) || continue
        case "$name" in amdgpu|i915|xe)
            for tf in "$h"/temp*_input; do
                [ -f "$tf" ] || continue
                base=$(basename "$tf")
                lab="?"
                [ -f "${tf%_input}_label" ] && lab=$(cat "${tf%_input}_label")
                temp=$(( $(cat "$tf") / 1000 ))
                printf '%s:%s|%s %s (%s, %s°C)\n' "$name" "$base" "$name" "$base" "$lab" "$temp"
            done
        ;;
        esac
    done >> "$_tmp" 2>/dev/null || true

    if [ ! -s "$_tmp" ]; then
        echo "  (none found — using auto)"
        GPU_CHOICE="auto"
        rm -f "$_tmp"
        return
    fi

    _def=1
    _n=0
    while IFS='|' read -r _id _label; do
        _n=$((_n + 1))
        echo "  $_n) $_label"
        case "$_id" in nvidia:*) _def=$_n ;; esac
    done < "$_tmp"

    _pick=$(prompt_pick "GPU" "$_def" "$_n")
    GPU_CHOICE=$(sed -n "${_pick}p" "$_tmp" | cut -d'|' -f1)
    rm -f "$_tmp"
    echo "  → $GPU_CHOICE"
}

pick_fan() {
    _tmp="$(mktemp)"

    echo ""
    echo "Select fan / pump RPM source:"

    for h in /sys/class/hwmon/hwmon*; do
        [ -f "$h/name" ] || continue
        name=$(cat "$h/name" 2>/dev/null) || continue
        for f in "$h"/fan*_input; do
            [ -f "$f" ] || continue
            base=$(basename "$f")
            lab="-"
            [ -f "${f%_input}_label" ] && lab=$(cat "${f%_input}_label")
            rpm=$(cat "$f" 2>/dev/null || echo 0)
            printf '%s/%s|%s %s (label=%s, %s RPM)\n' "$name" "$base" "$name" "$base" "$lab" "$rpm"
        done
    done >> "$_tmp" 2>/dev/null || true

    if [ ! -s "$_tmp" ]; then
        echo "  (none found — using auto)"
        FAN_CHOICE="auto"
        rm -f "$_tmp"
        return
    fi

    _def=1
    _n=0
    _best_rpm=-1
    _found_pump=0
    while IFS='|' read -r _id _label; do
        _n=$((_n + 1))
        echo "  $_n) $_label"
        rpm=$(echo "$_label" | sed -n 's/.*, \([0-9]*\) RPM.*/\1/p')
        [ -z "$rpm" ] && rpm=0
        if [ "$_id" = "nct6687/fan2_input" ]; then
            _def=$_n
            _found_pump=1
        elif [ "$_found_pump" -eq 0 ] && [ "$rpm" -gt "$_best_rpm" ]; then
            _best_rpm=$rpm
            _def=$_n
        fi
    done < "$_tmp"

    _pick=$(prompt_pick "Fan/pump" "$_def" "$_n")
    FAN_CHOICE=$(sed -n "${_pick}p" "$_tmp" | cut -d'|' -f1)
    rm -f "$_tmp"
    echo "  → $FAN_CHOICE"
}

write_cfg() {
    mkdir -p "$HOME/.config"
    cat > "$CFG" <<EOF
# Paradox AIO LCD — generated by install.sh
# GPU: auto | nvidia:<index> | amdgpu:<tempN_input> | i915:<tempN_input> | xe:<tempN_input>
# FAN: auto | <chip>/<fanN_input>
GPU=$GPU_CHOICE
FAN=$FAN_CHOICE
EOF
    echo "config → $CFG"
}

# ---- main ----
if [ -z "$GPU_CHOICE" ]; then
    pick_gpu
fi
if [ -z "$FAN_CHOICE" ]; then
    pick_fan
fi

echo ""
echo "[1/6] write config"
write_cfg

echo "[2/6] udev rule (needs sudo)"
# must sort before 73-seat-late.rules, which is what applies the uaccess ACL
sudo rm -f /etc/udev/rules.d/99-aio-paradox.rules   # stale name from earlier installs
sudo cp "$DIR/60-aio-paradox.rules" /etc/udev/rules.d/60-aio-paradox.rules
sudo udevadm control --reload-rules
sudo udevadm trigger -c add -s hidraw

echo "[3/6] driver + GUI"
mkdir -p "$HOME/.local/bin"
cp "$DIR/aio-lcd.py" "$HOME/.local/bin/aio-lcd.py"
cp "$DIR/aio-lcd-gui.py" "$HOME/.local/bin/aio-lcd-gui.py"
chmod +x "$HOME/.local/bin/aio-lcd.py" "$HOME/.local/bin/aio-lcd-gui.py"

echo "[4/6] desktop entry"
# %h is not a valid Exec field code — bake absolute path so app menus work
mkdir -p "$HOME/.local/share/applications"
_gui="$HOME/.local/bin/aio-lcd-gui.py"
sed "s|^Exec=.*|Exec=$_gui|; s|^TryExec=.*|TryExec=$_gui|" \
  "$DIR/aio-lcd-gui.desktop" > "$HOME/.local/share/applications/aio-lcd-gui.desktop"
command -v update-desktop-database >/dev/null 2>&1 \
  && update-desktop-database "$HOME/.local/share/applications" >/dev/null 2>&1 \
  || true

echo "[5/6] systemd user service"
mkdir -p "$HOME/.config/systemd/user"
cp "$DIR/aio-lcd.service" "$HOME/.config/systemd/user/aio-lcd.service"
systemctl --user daemon-reload

echo "[6/6] enable + start"
systemctl --user enable --now aio-lcd.service
systemctl --user restart aio-lcd.service
systemctl --user is-active aio-lcd.service

echo ""
echo "done. GPU=$GPU_CHOICE FAN=$FAN_CHOICE"
echo "GUI: aio-lcd-gui.py   (or launch “Paradox AIO LCD” from the app menu)"
echo "reconfigure: GUI Settings, or edit $CFG && systemctl --user restart aio-lcd"
